# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Generate a beta apk"
  lane :beta do
    gradle(
      task: "clean assemble",
      build_type: "Release"
    )
  end

  desc "Generate an app bundle"
  lane :bundle do
    gradle(
      task: "clean bundle",
      build_type: "Release"
    )
  end

  desc "Deploy a new app bundle to the Google Play Store"
  lane :deploy do
    # Generate an app bundle
    gradle(
      task: "clean bundle",
      build_type: "Release"
    )
    # Upload the app bundle to the google play store
    #upload_to_play_store
  end
end
