name: build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env: 
          MAPBOX_ACCESS_TOKEN:${{ secrets.MAPBOX_ACCESS_TOKEN }
