name: build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
      MAPBOX_PUBLIC_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run Unit Tests
        run: ./gradlew test -PMAPBOX_DOWNLOAD_TOKEN="${MAPBOX_DOWNLOAD_TOKEN} -PMAPBOX_PUBLIC_TOKEN="${MAPBOX_PUBLIC_TOKEN} -PSENTRY_DSN="${SENTRY_DSN}"
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug -PMAPBOX_DOWNLOAD_TOKEN="${MAPBOX_DOWNLOAD_TOKEN} -PMAPBOX_PUBLIC_TOKEN="${MAPBOX_PUBLIC_TOKEN} -PSENTRY_DSN="${SENTRY_DSN}"
