name: build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env: 
          MAPBOX_ACCESS_TOKEN:${{ secrets.MAPBOX_ACCESS_TOKEN }}
      - shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
          echo ${MAPBOX_ACCESS_TOKEN} > ~/.gradle/gradle.properties 
